// Catálogo Pregos Triângulo: dados migrados do site antigo (acentos corrigidos).
// Para editar: altere apenas este arquivo.

window.CATALOGO = [
  {
    id: 'com-cabeca',
    nome: 'Com cabeça',
    resumo: 'O prego comum, usado da marcenaria ao escoramento de obra.',
    uso: 'Construção civil, marcenaria, embalagens',
    colunas: ['Medida', 'POL / BWG', 'Aplicação'],
    itens: [
      ['8 x 8', '3/4 x 18', 'Marcenaria, mobiliário'],
      ['10 x 10', '7/8 x 17', 'Embalagens, marcenaria e acabamento'],
      ['12 x 12', '1 x 16', 'Embalagens, marcenaria e acabamento'],
      ['13 x 15', '1 1/4 x 15', 'Caixas para frutas e verduras'],
      ['13 x 18', '1 1/2 x 15', 'Caixas para frutas e verduras'],
      ['14 x 18', '1 1/2 x 14', 'Caixas para frutas e verduras'],
      ['14 x 21', '1 3/4 x 14', 'Caixas para frutas e verduras'],
      ['14 x 24', '2 x 14', 'Ripas, telhados, caixas para frutas e verduras'],
      ['15 x 15', '1 1/4 x 13', 'Ripas, telhados, caixas para frutas e verduras'],
      ['15 x 18', '1 1/2 x 13', 'Ripas, telhados, caixas para frutas e verduras'],
      ['15 x 21', '1 3/4 x 13', 'Ripas, telhados, caixas para frutas e verduras'],
      ['15 x 27', '2 1/2 x 13', 'Ripas, telhados, caixas para frutas e verduras'],
      ['16 x 18', '1 1/2 x 12', 'Lambris, carpintaria'],
      ['16 x 21', '1 3/4 x 12', 'Lambris, carpintaria'],
      ['16 x 24', '2 x 12', 'Lambris, móveis'],
      ['16 x 27', '2 1/2 x 12', 'Lambris, caixarias para concreto'],
      ['17 x 21', '1 3/4 x 11', 'Escoramentos, caibros, caixarias para concreto'],
      ['17 x 24', '2 x 11', 'Escoramentos, caibros, caixarias para concreto'],
      ['17 x 27', '2 1/2 x 11', 'Escoramentos, caibros, caixarias para concreto'],
      ['18 x 24', '2 x 10', 'Assoalhos de carrocerias, fôrmas para concreto, escoramentos, caibros'],
      ['18 x 27', '2 1/2 x 10', 'Caixaria de concreto, escoramento, caibros'],
      ['18 x 27 Galvanizado', '2 1/2 x 10', 'Telhado'],
      ['18 x 30', '2 3/4 x 10', 'Escoramento, caibros'],
      ['18 x 33', '3 x 10', 'Escoramento, caibros'],
      ['18 x 36', '3 1/4 x 10', 'Escoramento, caibros'],
      ['19 x 27', '2 1/2 x 9', 'Caixaria de concreto'],
      ['19 x 33', '3 x 9', 'Caibral, escoramento, escadas, fechamento de fôrmas'],
      ['19 x 36', '3 1/4 x 9', 'Caibral, porta, escoramento, escadas, fechamento de fôrmas'],
      ['19 x 39', '3 1/2 x 9', 'Caibral, porta, escoramento, escadas, fechamento de fôrmas'],
      ['19 x 42', '3 1/4 x 9', 'Caibral, porta, escoramento, escadas, fechamento de fôrmas'],
      ['20 x 30', '2 3/4 x 8', 'Caibral, escoramento, escadas, fechamento de fôrmas'],
      ['20 x 36', '3 1/4 x 8', 'Caibral, escoramento, escadas, fechamento de fôrmas'],
      ['20 x 42', '3 3/4 x 8', 'Escoramento, escadas, fechamento de fôrmas, portal'],
      ['20 x 42 Galvanizado', '3 3/4 x 8', 'Telhado'],
      ['20 x 48', '4 1/4 x 8', 'Escoramento, escadas, fechamento de fôrmas, portal'],
      ['22 x 42', '3 3/4 x 6', 'Portal'],
      ['22 x 48', '4 1/4 x 6', 'Portal'],
      ['22 x 54', '5 x 6', 'Portal'],
      ['23 x 54', '5 x 4', 'Mata-burros'],
      ['24 x 60', '5 1/2 x 3', 'Mata-burros, garimpos'],
      ['26 x 27', '2 1/2 x 1', 'Mata-burros, garimpos'],
      ['26 x 72', '6 1/2 x 1', 'Mata-burros, garimpos'],
    ],
  },
  {
    id: 'cabeca-dupla',
    nome: 'Cabeça dupla',
    resumo: 'A segunda cabeça facilita a retirada na desforma. Indicado para fôrmas e andaimes.',
    uso: 'Fôrmas para concreto, andaimes',
    colunas: ['Medida', 'POL / BWG', 'Aplicação'],
    itens: [
      ['17 x 27', '2 1/2 x 11', 'Construção civil, fôrmas para concreto e andaimes'],
      ['18 x 27', '2 1/2 x 10', 'Construção civil, fôrmas para concreto e andaimes'],
      ['18 x 30', '2 3/4 x 10', 'Construção civil, fôrmas para concreto e andaimes'],
    ],
  },
  {
    id: 'sem-cabeca',
    nome: 'Sem cabeça',
    resumo: 'Cabeça mínima, que fica quase invisível na madeira. Para acabamento, rodapés e molduras.',
    uso: 'Marcenaria, rodapés, molduras, assoalho',
    colunas: ['Medida', 'POL / BWG', 'Aplicação'],
    itens: [
      ['8 x 8', '3/4 x 18', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['10 x 10', '7/8 x 17', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['12 x 12', '1 x 16', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['13 x 15', '1 1/4 x 15', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['13 x 18', '1 1/2 x 15', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['13 x 21', '1 3/4 x 15', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['14 x 18', '1 1/2 x 14', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['15 x 15', '1 1/4 x 13', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['15 x 18', '1 1/2 x 13', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['15 x 21', '1 3/4 x 13', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['16 x 18', '1 1/2 x 12', 'Marcenaria em geral, mobiliário, rodapé, molduras de portas e janelas'],
      ['16 x 21', '1 3/4 x 12', 'Assoalho e marcenaria em geral, mobiliário, rodapé, molduras'],
      ['16 x 24', '2 x 12', 'Assoalho e marcenaria em geral, mobiliário, rodapé, molduras'],
      ['16 x 27', '2 1/2 x 12', 'Assoalho e marcenaria em geral, mobiliário, rodapé, molduras'],
      ['17 x 21', '1 3/4 x 11', 'Assoalho e marcenaria em geral, mobiliário, rodapé, molduras'],
      ['17 x 24', '2 x 11', 'Marcenaria em geral'],
      ['17 x 27', '2 1/2 x 11', 'Marcenaria em geral'],
      ['18 x 24', '2 x 10', 'Marcenaria em geral'],
      ['18 x 27', '2 1/2 x 10', 'Marcenaria em geral'],
      ['18 x 30', '2 3/4 x 10', 'Marcenaria em geral'],
      ['22 x 48', '4 1/4 x 6', 'Marcenaria em geral'],
    ],
  },
  {
    id: 'ardox',
    nome: 'Ardox',
    resumo: 'Haste espiralada com alta resistência ao arrancamento.',
    uso: 'Fixações que exigem alta ancoragem',
    indisponivel: true,
    colunas: ['Medida', 'POL / BWG', 'Aplicação'],
    itens: [],
  },
  {
    id: 'telhado',
    nome: 'Telhado',
    resumo: 'Cabeça tipo guarda-chuva, para fixação de telhas.',
    uso: 'Telhas de fibrocimento e coberturas',
    colunas: ['Medida', 'POL / BWG', 'Aplicação'],
    itens: [
      ['18 x 27', '2 1/2 x 10', 'Para telhados'],
      ['18 x 36', '3 1/4 x 10', 'Para telhados'],
    ],
  },
  {
    id: 'grampos',
    nome: 'Grampos',
    resumo: 'Grampo em U para prender o arame da cerca no mourão.',
    uso: 'Cercas rurais e divisas',
    colunas: ['POL / BWG', 'Aplicação'],
    itens: [
      ['7/8 x 11', 'Grampos para cercas'],
      ['7/8 x 12', 'Grampos para cercas'],
      ['1 x 10', 'Grampos para cercas'],
      ['1 x 10 Galvanizado', 'Grampos para cercas'],
      ['1 x 9', 'Grampos para cercas'],
    ],
  },
  {
    id: 'taco',
    nome: 'Taco',
    resumo: 'Prego para fixação de tacos e pisos de madeira.',
    uso: 'Pisos de taco e assoalhos',
    colunas: ['POL / BWG', 'Aplicação'],
    itens: [
      ['15 x 7/8', 'Fixação de tacos de madeira'],
    ],
  },
  {
    id: 'arames',
    nome: 'Arames',
    resumo: 'Arame recozido maleável, em rolos comerciais e industriais.',
    uso: 'Amarração de ferragens, uso geral',
    colunas: ['Bitola', 'Rolo comercial', 'Rolo industrial'],
    itens: [
      ['BWG nº 08', '1 kg', '35 kg'],
      ['BWG nº 10', '1 kg', '35 kg'],
      ['BWG nº 12', '1 kg', '35 kg'],
      ['BWG nº 14', '1 kg', '35 kg'],
      ['BWG nº 16', '1 kg', '35 kg'],
      ['BWG nº 18', '1 kg', '35 kg'],
      ['BWG nº 18 torcido', '1 kg', '35 kg'],
    ],
  },
];

// Ícones de linha (48x48) por categoria
window.ICONES = {
  'com-cabeca': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 8h20"/><path d="M24 8v28l-2 4h4l-2-4"/></svg>',
  'cabeca-dupla': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 6h18"/><path d="M16 14h16"/><path d="M24 6v30l-2 4h4l-2-4"/></svg>',
  'sem-cabeca': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 8h6"/><path d="M24 8v28l-2 4h4l-2-4"/></svg>',
  'ardox': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 8h20"/><path d="M24 8v28l-2 4h4l-2-4"/><path d="M20 16l8 3M20 22l8 3M20 28l8 3"/></svg>',
  'telhado': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 14c4-6 20-6 24 0"/><path d="M24 9v27l-2 4h4l-2-4"/></svg>',
  'grampos': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 40V20a8 8 0 0 1 16 0v20"/><path d="M14 40l2 3 2-3M30 40l2 3 2-3"/></svg>',
  'taco': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M13 14h22"/><path d="M24 14v16l-3 5h6l-3-5"/></svg>',
  'arames': '<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="24" cy="24" rx="16" ry="16"/><ellipse cx="24" cy="24" rx="11" ry="11"/><ellipse cx="24" cy="24" rx="6" ry="6"/></svg>',
};
